### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Klipper/readme](https://hosted.weblate.org/projects/klipper/readme/).

It also includes following components:

* [Klipper/BLTouch](https://hosted.weblate.org/projects/klipper/bltouch/)

* [Klipper/Bootloaders](https://hosted.weblate.org/projects/klipper/bootloaders/)

* [Klipper/Delta_Calibrate](https://hosted.weblate.org/projects/klipper/delta_calibrate/)

* [Klipper/Config_checks](https://hosted.weblate.org/projects/klipper/config_checks/)

* [Klipper/Measuring_Resonances](https://hosted.weblate.org/projects/klipper/measuring_resonances/)

* [Klipper/Hall_Filament_Width_Sensor](https://hosted.weblate.org/projects/klipper/hall_filament_width_sensor/)

* [Klipper/Contact](https://hosted.weblate.org/projects/klipper/contact/)

* [Klipper/Bed_Level](https://hosted.weblate.org/projects/klipper/bed_level/)

* [Klipper/Benchmarks](https://hosted.weblate.org/projects/klipper/benchmarks/)

* [Klipper/Rotation_Distance](https://hosted.weblate.org/projects/klipper/rotation_distance/)

* [Klipper/Slicers](https://hosted.weblate.org/projects/klipper/slicers/)

* [Klipper/Bed_Mesh](https://hosted.weblate.org/projects/klipper/bed_mesh/)

* [Klipper/MCU_Commands](https://hosted.weblate.org/projects/klipper/mcu_commands/)

* [Klipper/Example_Configs](https://hosted.weblate.org/projects/klipper/example_configs/)

* [Klipper/Skew_Correction](https://hosted.weblate.org/projects/klipper/skew_correction/)

* [Klipper/Multi_MCU_Homing](https://hosted.weblate.org/projects/klipper/multi_mcu_homing/)

* [Klipper/TMC_Drivers](https://hosted.weblate.org/projects/klipper/tmc_drivers/)

* [Klipper/Using_PWM_Tools](https://hosted.weblate.org/projects/klipper/using_pwm_tools/)

* [Klipper/G-Codes](https://hosted.weblate.org/projects/klipper/g-codes/)

* [Klipper/Releases](https://hosted.weblate.org/projects/klipper/releases/)

* [Klipper/Pressure_Advance](https://hosted.weblate.org/projects/klipper/pressure_advance/)

* [Klipper/Packaging](https://hosted.weblate.org/projects/klipper/packaging/)

* [Klipper/CANBUS](https://hosted.weblate.org/projects/klipper/canbus/)

* [Klipper/Status_Reference](https://hosted.weblate.org/projects/klipper/status_reference/)

* [Klipper/Endstop_Phase](https://hosted.weblate.org/projects/klipper/endstop_phase/)

* [Klipper/Command_Templates](https://hosted.weblate.org/projects/klipper/command_templates/)

* [Klipper/Resonance_Compensation](https://hosted.weblate.org/projects/klipper/resonance_compensation/)

* [Klipper/index](https://hosted.weblate.org/projects/klipper/index/)

* [Klipper/Features](https://hosted.weblate.org/projects/klipper/features/)

* [Klipper/Config_Reference](https://hosted.weblate.org/projects/klipper/config_reference/)

* [Klipper/Debugging](https://hosted.weblate.org/projects/klipper/debugging/)

* [Klipper/Navigation](https://hosted.weblate.org/projects/klipper/navigation/)

* [Klipper/Kinematics](https://hosted.weblate.org/projects/klipper/kinematics/)

* [Klipper/SDCard_Updates](https://hosted.weblate.org/projects/klipper/sdcard_updates/)

* [Klipper/Overview](https://hosted.weblate.org/projects/klipper/overview/)

* [Klipper/CONTRIBUTING](https://hosted.weblate.org/projects/klipper/contributing/)

* [Klipper/API_Server](https://hosted.weblate.org/projects/klipper/api_server/)

* [Klipper/Code_Overview](https://hosted.weblate.org/projects/klipper/code_overview/)

* [Klipper/TSL1401CL_Filament_Width_Sensor](https://hosted.weblate.org/projects/klipper/tsl1401cl_filament_width_sensor/)

* [Klipper/RPi_microcontroller](https://hosted.weblate.org/projects/klipper/rpi_microcontroller/)

* [Klipper/Protocol](https://hosted.weblate.org/projects/klipper/protocol/)

* [Klipper/Beaglebone](https://hosted.weblate.org/projects/klipper/beaglebone/)

* [Klipper/Config_Changes](https://hosted.weblate.org/projects/klipper/config_changes/)

* [Klipper/FAQ](https://hosted.weblate.org/projects/klipper/faq/)

* [Klipper/Manual_Level](https://hosted.weblate.org/projects/klipper/manual_level/)

* [Klipper/CANBUS_protocol](https://hosted.weblate.org/projects/klipper/canbus_protocol/)

* [Klipper/Probe_Calibrate](https://hosted.weblate.org/projects/klipper/probe_calibrate/)

* [Klipper/Installation](https://hosted.weblate.org/projects/klipper/installation/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by ghost** [comment]
Greetings!

If I want to translate Klipper into Hungarian, where can I find the related language files? Can you help me with that? I would love to join in Hungarian!

Thanks for the help!

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by dingyifei** [comment]
> Greetings!
> 
> 
> 
> If I want to translate Klipper into Hungarian, where can I find the related language files? Can you help me with that? I would love to join in Hungarian!
> 
> 
> 
> Thanks for the help!
> 
> 
> 
> Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

Hi,

Thank you for your interest!

you can just add it through Weblate, go int any component and add Hungarian, everything will be automatically generated by Weblate 

I'm currently working on fixing the search index, so the translations are not included in klipper3d.org as of now.

**Comment by ghost** [comment]
> 

Hi! Thanks for the reply. Then I'll find out how it works.

**Comment by ghost** [comment]
> > Greetings!
> > If I want to translate Klipper into Hungarian, where can I find the related language files? Can you help me with that? I would love to join in Hungarian!
> > Thanks for the help!
> > Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)
> 
> Hi,
> 
> Thank you for your interest!
> 
> you can just add it through Weblate, go int any component and add Hungarian, everything will be automatically generated by Weblate
> 
> I'm currently working on fixing the search index, so the translations are not included in klipper3d.org as of now.

I went to the Host Weblate page but I don't understand how the Hungarian translation and pasting works. Is there a description for it?

**Comment by dingyifei** [comment]
image
You can click on start new translation to add any language. I just added `hu` Hungarian.

You can access it through https://hosted.weblate.org/languages/hu/klipper/ The language files will appear in this repository after the next pull request generated by weblate.

**Comment by ghost** [comment]
> 
> image You can click on start new translation to add any language. I just added `hu` Hungarian.
> 
> You can access it through https://hosted.weblate.org/languages/hu/klipper/ The language files will appear in this repository after the next pull request generated by weblate.

Ooohh super. Thanks!

**Comment by ghost** [comment]
What happened to the website? Not available.
Screenshot_20220325-124213

**Comment by dingyifei** [comment]
> What happened to the website? Not available. Screenshot_20220325-124213

I guess the Weblate.org server was down. It is a hosted Weblate project, so it depends on Weblate service.

The server seems to be up now.

**Pull request merged**
