### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Klipper/readme](https://hosted.weblate.org/projects/klipper/readme/).

It also includes following components:

* [Klipper/Code_Overview](https://hosted.weblate.org/projects/klipper/code_overview/)

* [Klipper/Packaging](https://hosted.weblate.org/projects/klipper/packaging/)

* [Klipper/Delta_Calibrate](https://hosted.weblate.org/projects/klipper/delta_calibrate/)

* [Klipper/Config_checks](https://hosted.weblate.org/projects/klipper/config_checks/)

* [Klipper/CANBUS](https://hosted.weblate.org/projects/klipper/canbus/)

* [Klipper/Hall_Filament_Width_Sensor](https://hosted.weblate.org/projects/klipper/hall_filament_width_sensor/)

* [Klipper/Contact](https://hosted.weblate.org/projects/klipper/contact/)

* [Klipper/Benchmarks](https://hosted.weblate.org/projects/klipper/benchmarks/)

* [Klipper/Bed_Level](https://hosted.weblate.org/projects/klipper/bed_level/)

* [Klipper/Rotation_Distance](https://hosted.weblate.org/projects/klipper/rotation_distance/)

* [Klipper/Slicers](https://hosted.weblate.org/projects/klipper/slicers/)

* [Klipper/Bed_Mesh](https://hosted.weblate.org/projects/klipper/bed_mesh/)

* [Klipper/MCU_Commands](https://hosted.weblate.org/projects/klipper/mcu_commands/)

* [Klipper/Skew_Correction](https://hosted.weblate.org/projects/klipper/skew_correction/)

* [Klipper/Using_PWM_Tools](https://hosted.weblate.org/projects/klipper/using_pwm_tools/)

* [Klipper/Resonance_Compensation](https://hosted.weblate.org/projects/klipper/resonance_compensation/)

* [Klipper/G-Codes](https://hosted.weblate.org/projects/klipper/g-codes/)

* [Klipper/Pressure_Advance](https://hosted.weblate.org/projects/klipper/pressure_advance/)

* [Klipper/Endstop_Phase](https://hosted.weblate.org/projects/klipper/endstop_phase/)

* [Klipper/Command_Templates](https://hosted.weblate.org/projects/klipper/command_templates/)

* [Klipper/index](https://hosted.weblate.org/projects/klipper/index/)

* [Klipper/Features](https://hosted.weblate.org/projects/klipper/features/)

* [Klipper/Kinematics](https://hosted.weblate.org/projects/klipper/kinematics/)

* [Klipper/SDCard_Updates](https://hosted.weblate.org/projects/klipper/sdcard_updates/)

* [Klipper/API_Server](https://hosted.weblate.org/projects/klipper/api_server/)

* [Klipper/Example_Configs](https://hosted.weblate.org/projects/klipper/example_configs/)

* [Klipper/TSL1401CL_Filament_Width_Sensor](https://hosted.weblate.org/projects/klipper/tsl1401cl_filament_width_sensor/)

* [Klipper/Beaglebone](https://hosted.weblate.org/projects/klipper/beaglebone/)

* [Klipper/FAQ](https://hosted.weblate.org/projects/klipper/faq/)

* [Klipper/Debugging](https://hosted.weblate.org/projects/klipper/debugging/)

* [Klipper/Probe_Calibrate](https://hosted.weblate.org/projects/klipper/probe_calibrate/)

* [Klipper/Installation](https://hosted.weblate.org/projects/klipper/installation/)

* [Klipper/Navigation](https://hosted.weblate.org/projects/klipper/navigation/)

* [Klipper/Config_Reference](https://hosted.weblate.org/projects/klipper/config_reference/)

* [Klipper/CANBUS_protocol](https://hosted.weblate.org/projects/klipper/canbus_protocol/)

* [Klipper/Config_Changes](https://hosted.weblate.org/projects/klipper/config_changes/)

* [Klipper/BLTouch](https://hosted.weblate.org/projects/klipper/bltouch/)

* [Klipper/Manual_Level](https://hosted.weblate.org/projects/klipper/manual_level/)

* [Klipper/Overview](https://hosted.weblate.org/projects/klipper/overview/)

* [Klipper/RPi_microcontroller](https://hosted.weblate.org/projects/klipper/rpi_microcontroller/)

* [Klipper/CONTRIBUTING](https://hosted.weblate.org/projects/klipper/contributing/)

* [Klipper/Releases](https://hosted.weblate.org/projects/klipper/releases/)

* [Klipper/Protocol](https://hosted.weblate.org/projects/klipper/protocol/)

* [Klipper/Multi_MCU_Homing](https://hosted.weblate.org/projects/klipper/multi_mcu_homing/)

* [Klipper/Status_Reference](https://hosted.weblate.org/projects/klipper/status_reference/)

* [Klipper/Bootloaders](https://hosted.weblate.org/projects/klipper/bootloaders/)

* [Klipper/Measuring_Resonances](https://hosted.weblate.org/projects/klipper/measuring_resonances/)

* [Klipper/TMC_Drivers](https://hosted.weblate.org/projects/klipper/tmc_drivers/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by dingyifei** [comment]
@AntoszHUN hi, looks like you have translated nearly 75% of the strings to Hungarian now. Do you want to create a pull request to enable the Hungarian translation on klipper3d.org?

**Comment by ghost** [comment]
> 



> @AntoszHUN hi, looks like you have translated nearly 75% of the strings to Hungarian now. Do you want to create a pull request to enable the Hungarian translation on klipper3d.org?

Hi! Yes. I would definitely like to apply. But I don't know yet how it can be.

**Comment by dingyifei** [comment]
> > 
> 
> 
> 
> 
> 
> 
> 
> > @AntoszHUN hi, looks like you have translated nearly 75% of the strings to Hungarian now. Do you want to create a pull request to enable the Hungarian translation on klipper3d.org?
> 
> 
> 
> Hi! Yes. I would definitely like to apply. But I don't know yet how it can be.

basically,active_translations is a file for the multi-language site building script to know what language to include in klipper3d.org. The directory name is the language folder, site language is the language code for mkdocs material plug-in's language setting, the displayed language is the text users will see when they hover their mouse on the "globe" button, and the search language is the language code for mkdocs material plug-in's search index language setting.

https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=langua

https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search#built-in-search-plugin

Current content:

```
#Directory Name,Site Language,Displayed Language Name,Search Language,Comments
zh_Hans,zh,简体中文,ja,
zh_Hant,zh-Hant,繁體中文,ja,
```

**Comment by ghost** [comment]
I do not really understand. I'll do the translation. But the rest is high for me.

**Comment by dingyifei** [comment]
> I do not really understand. I'll do the translation. But the rest is high for me.

I guess I can add the translation to klipper3d.org for you, just need one thing for it to be properly displayed on klipper3d.org: Hungarian(the language) in Hungarian

This word will be displayed in the language selector image

**Comment by ghost** [comment]
> I guess I can add the translation to klipper3d.org for you, just need one thing for it to be properly displayed on klipper3d.org: Hungarian(the language) in Hungarian
> 
> This word will be displayed in the language selector

I understand and thank you! The Hungarian language in Hungarian looks like this: Magyar

**Comment by dingyifei** [comment]
#244

**Pull request merged**
