### PR TITLE
Update README with korean translation section

### PR DESCRIPTION
**Pull request by gouache**
Hello.
This is my first PR for contributing korean section.
I'm happy to contribute!

### CODE REVIEW

**Comment by dingyifei** [comment]
Thank you for your contribution!

**Comment by gouache** [comment]
> Thank you for your contribution!

I have a question about weblate.
there's an alert in weblate site regarding 'failed to merge'
how can I fix it or could you fix it?

**Comment by dingyifei** [comment]
Sorry, I think I accidentally blew up the Weblate repo for a second... I'm not very familiar with the current setup and accidentally rebased this PR before I rebased the PR from Weblate, which led to a manual merge. It's now fixed! 

Thank you for reminding me 👍🏼

**Comment by gouache** [comment]
> Sorry, I think I accidentally blew up the Weblate repo for a second... I'm not very familiar with the current setup and accidentally rebased this PR before I rebased the PR from Weblate, which led to a manual merge. It's now fixed!
> 
> Thank you for reminding me 👍🏼

thanks~ I found merge problem is fixed, but my new translations are not generated to new pull request.
is there any other problem remained?

**Comment by dingyifei** [comment]
> thanks~ I found merge problem is fixed, but my new translations are not generated to new pull request.
> 
> is there any other problem remained?

nah, it will generate pr every 24hrs to reduce the number of commits it generate.

**Pull request merged**
