### PR TITLE
active_translations: Activate Hungarian

### PR DESCRIPTION
**Pull request by dingyifei**
Will merge once the translation reaches 75%

Signed-off-by: Yifei Ding<yifeiding@protonmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
Ohh super! Thank you very much for your help! I do the translation on a daily basis. I keep going with it. Obviously errors can occur, but once it’s completely done and I see it on the website, I can correct the errors afterwards. I hope you will have the opportunity.

Thanks again!

**Comment by dingyifei** [comment]
merged, will show up on klipper3d.org within 24 hr (if everything is working)

**Comment by ghost** [comment]
> merged, will show up on klipper3d.org within 24 hr (if everything is working)

All right! Thank you very much!

**Comment by ghost** [comment]
Hi! I see the Hungarian language works. There is still room for improvement. Some links do not work. I'll fix them soon.

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by dingyifei** [comment]
> Hi! I see the Hungarian language works. There is still room for improvement. Some links do not work. I'll fix them soon.
> 
> 
> 
> Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

you can also change the displayed text part of the links

**Comment by ghost** [comment]
> 



> > Hi! I see the Hungarian language works. There is still room for improvement. Some links do not work. I'll fix them soon.
> > Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)
> 
> you can also change the displayed text part of the links

All right.

**Comment by ghost** [comment]
Hi! I'm done with the Hungarian language. It is now 100%. There must be bugs in it, but as soon as they show up, I'll fix them. I am now checking / reviewing 80% of the time and fixing bugs. 

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Pull request merged**
