### PR TITLE
Fix lint issues to pass the workflow test

### PR DESCRIPTION
**Pull request by alfrix**

### CODE REVIEW

**Comment by dingyifei** [comment]
I'm not really sure if the lint issues can ever be fixed because localized md files are generated through mdpo. I think a potential solution may be a post processing script.

**Comment by alfrix** [comment]
i just fixed a bunch of this issues directly on weblate, only the pwm tools file should remain to figure out why the indent on a newline that is added

**Comment by dingyifei** [comment]
I think the indent is caused by mdpo. It does weird things often and I'm unsure if there is a fix. I'm really not sure if fixing it is beneficial since I'm not planning to merge all the changes to klipper3d/klipper rn.

**Comment by alfrix** [comment]
changed to skip whitespace check of the `docs` folder and fix scripts lint

**Pull request merged**
