### PR TITLE
Update Hungarian language

### PR DESCRIPTION
**Pull request by ghost**
I'm done with the Hungarian translation.

 - The translation is 100% complete.
 - I checked the translation.
 - I also fixed other bugs that were only detected by a program called Poedit.
 - I will keep the translation up to date, which I check on a weekly basis.
 - Remove .mo files.

Thank you for the team's contribution and help!

Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)

### CODE REVIEW

**Comment by ghost** [comment]
Is the collision possible because of a program called POEDIT? Unfortunately, it was only there that I was able to better review and edit certain topics. because I had to search for words and replace them. I hope it will be good for that. I would ask for information on the merger if possible.

Thanks in advance!

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by ghost** [comment]
Fixed conflicts in files. If I see it right, it's good now.

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by dingyifei** [comment]
> Fixed conflicts in files. If I see it right, it's good now.
> 
> Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)

It works now! Thank you for your contribution!

**Comment by ghost** [comment]
When will the finished translation be visible on the website?

**Comment by dingyifei** [comment]
> 

It should be already visible on the website, the changes take some time to appear

Additionally, the table of content is currently not translatable, I still need to write some shell script to make it work. 

You can view the translation at https://www.klipper3d.org/hu/ 

If you have changed the index page, I'll try to update that (manually) when I have some time.

**Comment by ghost** [comment]
> 



> > 
> 
> It should be already visible on the website, the changes take some time to appear
> 
> Additionally, the table of content is currently not translatable, I still need to write some shell script to make it work.
> 
> You can view the translation at https://www.klipper3d.org/hu/
> 
> If you have changed the index page, I'll try to update that (manually) when I have some time.

All right! Thank you very much!

**Comment by ghost** [comment]
Hi! To this day, I do not see the update. Is there information on when it will appear on the website?

**Comment by dingyifei** [comment]
> Hi! To this day, I do not see the update. Is there information on when it will appear on the website?

There is an merge conflict on Weblate. I'm very busy the past week and haven't fix it. I'll try to fix it today.

**Comment by ghost** [comment]
> > Hi! To this day, I do not see the update. Is there information on when it will appear on the website?
> 
> There is an merge conflict on Weblate. I'm very busy the past week and haven't fix it. I'll try to fix it today.

No problem. Unfortunately, I don’t have the level of access to fix it. Something went wrong. Could I have done something wrong?

**Comment by dingyifei** [comment]
> > > Hi! To this day, I do not see the update. Is there information on when it will appear on the website?
> 
> > 
> 
> > There is an merge conflict on Weblate. I'm very busy the past week and haven't fix it. I'll try to fix it today.
> 
> 
> 
> No problem. Unfortunately, I don’t have the level of access to fix it. Something went wrong. Could I have done something wrong?

It's my fault, I accidentally merged the upstream documentation update when you were editing on Weblate. 

It's fixed now! The next documentation deployment will happen after 7 hours. Let me know if the changes don't appear

**Comment by ghost** [comment]
> 



> > > > Hi! To this day, I do not see the update. Is there information on when it will appear on the website?
> > 
> > 
> > > 
> > 
> > 
> > > There is an merge conflict on Weblate. I'm very busy the past week and haven't fix it. I'll try to fix it today.
> > 
> > 
> > No problem. Unfortunately, I don’t have the level of access to fix it. Something went wrong. Could I have done something wrong?
> 
> It's my fault, I accidentally merged the upstream documentation update when you were editing on Weblate.
> 
> It's fixed now! The next documentation deployment will happen after 7 hours. Let me know if the changes don't appear

All right. Thanks! I won't edit it until then.

**Comment by ghost** [comment]
> > 
> 
> > > > > Hi! To this day, I do not see the update. Is there information on when it will appear on the website?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > There is an merge conflict on Weblate. I'm very busy the past week and haven't fix it. I'll try to fix it today.
> > > 
> > > 
> > > No problem. Unfortunately, I don’t have the level of access to fix it. Something went wrong. Could I have done something wrong?
> > 
> > 
> > It's my fault, I accidentally merged the upstream documentation update when you were editing on Weblate.
> > It's fixed now! The next documentation deployment will happen after 7 hours. Let me know if the changes don't appear
> 
> All right. Thanks! I won't edit it until then.

I have corrected the translation. I also saw that some text that needed to be translated was added. I have also translated these.

**Comment by ghost** [comment]
The Hungarian translation on klipper3d.org has not been updated yet. It does not match what is on the Weblate website. Is there any information about it? Maybe put it back on to merge it?

**Comment by dingyifei** [comment]
> The Hungarian translation on klipper3d.org has not been updated yet. It does not match what is on the Weblate website. Is there any information about it? Maybe put it back on to merge it?

klipper3d.org has a page update interval of 1 time a day. As a result, anything merged from Weblate needs around 24 hrs to show up. You can see the klipper deploy workflow history. I suspect the time I merged the updates was after the most recent execution of Klipper deploy. 

https://github.com/Klipper3d/klipper/actions

**Comment by ghost** [comment]
> 



> > The Hungarian translation on klipper3d.org has not been updated yet. It does not match what is on the Weblate website. Is there any information about it? Maybe put it back on to merge it?
> 
> klipper3d.org has a page update interval of 1 time a day. As a result, anything merged from Weblate needs around 24 hrs to show up. You can see the klipper deploy workflow history. I suspect the time I merged the updates was after the most recent execution of Klipper deploy.
> 
> https://github.com/Klipper3d/klipper/actions

I understand.

**Comment by ghost** [comment]
Hi!

It's been 20 days since the 100% Hungarian translation was posted. However, at klipper3d.org I still only see the old 70% translation that was included for the first time. What if someone did something? I took the trouble and time to translate the entire website in 2.5 months without regret. I want to wait for it to arrive on time and not have to wait for weeks. I find it interesting that the 70% translation came to the site in 24 hours that year. Can I get a substantive answer on this matter?

Thank you very much!

Sincerely!
Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by dingyifei** [comment]
> Hi!
> 
> 
> 
> It's been 20 days since the 100% Hungarian translation was posted. However, at klipper3d.org I still only see the old 70% translation that was included for the first time. What if someone did something? I took the trouble and time to translate the entire website in 2.5 months without regret. I want to wait for it to arrive on time and not have to wait for weeks. I find it interesting that the 70% translation came to the site in 24 hours that year. Can I get a substantive answer on this matter?
> 
> 
> 
> Thank you very much!
> 
> 
> 
> Sincerely!
> 
> Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

I'll investigate right now and give you an answer today

**Comment by dingyifei** [comment]
Actually the website is 99% translated except for the index page.

You can see "features" on klipper3d.org is not translated because manual-index.md is not automatically updated.

image

I have updated manual-index.md in this commit, which should address this issue
https://github.com/Klipper3d/klipper-translations/commit/770776ab7a85eec3c1e2ede9d20a93b63e93642a

On the left side, the table of content is not translated because the current implementation doesn't support translating it.

image

updates 10 days ago are actually up on klipper3d.org, for example, for API_Server.md, you can see the change on line 15 in this commit https://github.com/Klipper3d/klipper-translations/commit/bccdcc238e3ea46b0928ec277df881c351fd5263 is indeed represented on the website 


image

Is there anything I missed? If there are files that aren't synced properly, please let me know.

**Comment by ghost** [comment]
On the welcome screen, I corrected the 3-d caption at the beginning of the sentence to 3D in Hungarian. More aesthetic and real. I don't see that yet. Also, there are links that don't work. I translated everything into Hungarian. But this is what it looked like with the 70% translation. I don't want to argue, but I wrote to the Hungarian group that the translation of the page was ready, and I was shouted that it wasn't ready because it was incomplete. It's ready. Why can't I update all my files? Why do you do it one by one?

**Comment by dingyifei** [comment]
> On the welcome screen, I corrected the 3-d caption at the beginning of the sentence to 3D in Hungarian. More aesthetic and real. I don't see that yet. Also, there are links that don't work. I translated everything into Hungarian. But this is what it looked like with the 70% translation. I don't want to argue, but I wrote to the Hungarian group that the translation of the page was ready, and I was shouted that it wasn't ready because it was incomplete. It's ready. Why can't I update all my files? Why do you do it one by one?

I'm really sorry, the commit earlier about the index page is about the welcome screen and it shows up correctly now. The index page(welcome page) needs to be edited manually and committed through GitHub by editing the manual-index.md. I didn't realize the translation was changed later in the translation. I owe you and your Hungarian friends an apology. 

You can see it is the same as the most recent version now:

image

**Comment by dingyifei** [comment]
I should've explained it earlier. I'll add a reminder in the documentation.

image
The links that are linked to an internal section like the one above needs to be manually fixed through Weblate one by one.  

For example, in FAQ, the table of content is not working, and you can see text in the round bracket doesn't match the title of the section:

image

The way to fix it is to copy the section title and replace spaces with `-`, remove the hats on letters like `á`, and remove all symbols. I'm going to fix as much as possible before I go to sleep today. A fast way to fix it would be copy the link from the section title's little `p` thingy:

image

then put everything in the link after the hashtag `#` into the round bracket in Weblate strings.

image

For example:
image

It will cause a markdown link warning to appear on Weblate. You can omit these warnings, I'll try to disable the link checks.

**Comment by dingyifei** [comment]
I noticed some section titles are different to the table of content. for example, `Hogyan alakíthatok át egy Marlin tű számot Klipper tű névre?` vs `Hogyan konvertálhatok egy Marlin tűszámot egy Klipper tűnévre??`. I marked these strings as needs editing, let me know what you think.

**Comment by ghost** [comment]
> I noticed some section titles are different to the table of content. for example, `Hogyan alakíthatok át egy Marlin tű számot Klipper tű névre?` vs `Hogyan konvertálhatok egy Marlin tűszámot egy Klipper tűnévre??`. I marked these strings as needs editing, let me know what you think.

Yes. I corrected it because those words have to be written separately. Grammatically correct. I didn’t know that accented words aren’t good. Weblate didn't tell me that. The words have an accent. Otherwise the translation is unnecessary.

**Comment by dingyifei** [comment]
> 

I corrected most parts of the FAQ and fixed a few other links.  They should show up within 24 hours. Let me know if these fixes are working as intended.

**Comment by ghost** [comment]
> > 
> 
> I corrected most parts of the FAQ and fixed a few other links. They should show up within 24 hours. Let me know if these fixes are working as intended.

SORRY!! The text in parentheses was accidentally translated into Hungarian. And it shouldn't be. I'm sorry! I made a mistake! I'll fix the bugs as soon as I can. Only then will I have to review everything again.

**Comment by ghost** [comment]
I see I've managed to fix all the translation errors in the (# ...) sections. What is in such a place cannot be in Hungarian, because the links will not work. I wrote them back in their original language (English). Thanks for the sign! It will be good now. I reviewed everything on the weblate and related and improved it.

**Comment by dingyifei** [comment]
> I see I've managed to fix all the translation errors in the (# ...) sections. What is in such a place cannot be in Hungarian, because the links will not work. I wrote them back in their original language (English). Thanks for the sign! It will be good now. I reviewed everything on the weblate and related and improved it.

I wish I could explain it better in the earlier message.

Markdown relative links that addresses section titles need to match the titles.

For example, if the title is "aaaa bbbb cccc?" Then the link after # to address this title would be "aaaa-bbbb-cccc".

A few examples below:

"Abc abc" - "#abc-abc"
"abc ábc" - "#abc-abc"
"abc abc?" - "#abc-abc"



Actually I changed these links to Hungarian because the links need to match the section title. They don't work before because they are in English, and there is no matching sections the links can take you to. Everything after # need accents and symbols to be removed and spaces replaced with dash -. You can find the right link by clicking the little button next to the sections. image 

The link in the navigation bar will change to something like xxxx.html#yyyy-yyyy-yyyy, where everything after # can be used in a link to address the section and make the links work. 

If you couldn't fix them, let me know the exact link that doesn't work and I'll figure out a way to fix them

**Comment by ghost** [comment]
> 



> > I see I've managed to fix all the translation errors in the (# ...) sections. What is in such a place cannot be in Hungarian, because the links will not work. I wrote them back in their original language (English). Thanks for the sign! It will be good now. I reviewed everything on the weblate and related and improved it.
> 
> I wish I could explain it better in the earlier message.
> 
> Markdown relative links that addresses section titles need to match the titles.
> 
> For example, if the title is "aaaa bbbb cccc?" Then the link after # to address this title would be "aaaa-bbbb-cccc".
> 
> A few examples below:
> 
> "Abc abc" - "#abc-abc" "abc ábc" - "#abc-abc" "abc abc?" - "#abc-abc"
> 
> Actually I changed these links to Hungarian because the links need to match the section title. They don't work before because they are in English, and there is no matching sections the links can take you to. Everything after # need accents and symbols to be removed and spaces replaced with dash -. You can find the right link by clicking the little button next to the sections. image
> 
> The link in the navigation bar will change to something like xxxx.html#yyyy-yyyy-yyyy, where everything after # can be used in a link to address the section and make the links work.
> 
> If you couldn't fix them, let me know the exact link that doesn't work and I'll figure out a way to fix them

I looked at the page below. https://www.klipper3d.org/en/FAQ.html?h=adom#how-can-i-donate-to-the-project None of these links work here. So you say that the (# ...) equivalent of accented text is unaccented. I understand. Interesting because most of what works in English works. Then I'll fix it without a Hungarian accent.

**Comment by dingyifei** [comment]
> > 
> 
> 
> 
> 
> 
> 
> 
> > > I see I've managed to fix all the translation errors in the (# ...) sections. What is in such a place cannot be in Hungarian, because the links will not work. I wrote them back in their original language (English). Thanks for the sign! It will be good now. I reviewed everything on the weblate and related and improved it.
> 
> > 
> 
> > I wish I could explain it better in the earlier message.
> 
> > 
> 
> > Markdown relative links that addresses section titles need to match the titles.
> 
> > 
> 
> > For example, if the title is "aaaa bbbb cccc?" Then the link after # to address this title would be "aaaa-bbbb-cccc".
> 
> > 
> 
> > A few examples below:
> 
> > 
> 
> > "Abc abc" - "#abc-abc" "abc ábc" - "#abc-abc" "abc abc?" - "#abc-abc"
> 
> > 
> 
> > Actually I changed these links to Hungarian because the links need to match the section title. They don't work before because they are in English, and there is no matching sections the links can take you to. Everything after # need accents and symbols to be removed and spaces replaced with dash -. You can find the right link by clicking the little button next to the sections. image
> 
> > 
> 
> > The link in the navigation bar will change to something like xxxx.html#yyyy-yyyy-yyyy, where everything after # can be used in a link to address the section and make the links work.
> 
> > 
> 
> > If you couldn't fix them, let me know the exact link that doesn't work and I'll figure out a way to fix them
> 
> 
> 
> I looked at the page below. https://www.klipper3d.org/en/FAQ.html?h=adom#how-can-i-donate-to-the-project None of these links work here. So you say that the (# ...) equivalent of accented text is unaccented. I understand. Interesting because most of what works in English works. Then I'll fix it without a Hungarian accent.


I already applied a fix yesterday(I used unaccented equivalent and replaced the English text in #...), which should show up today. I'll check if my fix is working. Anything else I need to fix?

**Comment by ghost** [comment]
167915136-c3012c65-4233-4e88-9ee2-917682f8d10b

¶ What is this sign? I can't see it on a weblate.

**Comment by ghost** [comment]
> > > 
> > 
> > 
> > > > I see I've managed to fix all the translation errors in the (# ...) sections. What is in such a place cannot be in Hungarian, because the links will not work. I wrote them back in their original language (English). Thanks for the sign! It will be good now. I reviewed everything on the weblate and related and improved it.
> > 
> > 
> > > 
> > 
> > 
> > > I wish I could explain it better in the earlier message.
> > 
> > 
> > > 
> > 
> > 
> > > Markdown relative links that addresses section titles need to match the titles.
> > 
> > 
> > > 
> > 
> > 
> > > For example, if the title is "aaaa bbbb cccc?" Then the link after # to address this title would be "aaaa-bbbb-cccc".
> > 
> > 
> > > 
> > 
> > 
> > > A few examples below:
> > 
> > 
> > > 
> > 
> > 
> > > "Abc abc" - "#abc-abc" "abc ábc" - "#abc-abc" "abc abc?" - "#abc-abc"
> > 
> > 
> > > 
> > 
> > 
> > > Actually I changed these links to Hungarian because the links need to match the section title. They don't work before because they are in English, and there is no matching sections the links can take you to. Everything after # need accents and symbols to be removed and spaces replaced with dash -. You can find the right link by clicking the little button next to the sections. image
> > 
> > 
> > > 
> > 
> > 
> > > The link in the navigation bar will change to something like xxxx.html#yyyy-yyyy-yyyy, where everything after # can be used in a link to address the section and make the links work.
> > 
> > 
> > > 
> > 
> > 
> > > If you couldn't fix them, let me know the exact link that doesn't work and I'll figure out a way to fix them
> > 
> > 
> > I looked at the page below. https://www.klipper3d.org/en/FAQ.html?h=adom#how-can-i-donate-to-the-project None of these links work here. So you say that the (# ...) equivalent of accented text is unaccented. I understand. Interesting because most of what works in English works. Then I'll fix it without a Hungarian accent.
> 
> I already applied a fix yesterday(I used unaccented equivalent and replaced the English text in #...), which should show up today. I'll check if my fix is working. Anything else I need to fix?

I'll check back over the weekend to see what works.

**Comment by ghost** [comment]
Screenshot_20220512-053507~2
This section is also translated. But he didn't get on the page. This is the (Navigation) part if I know it.

**Comment by dingyifei** [comment]
> Screenshot_20220512-053507~2
> 
> This section is also translated. But he didn't get on the page. This is the (Navigation) part if I know it.

The "Navigation" in Weblate doesn't work because it needs a ton of manual adjustment to the website's configuration file and I haven't implement it yet. I'll try to implement them in the near future, but I really don't have a clue at the moment. 

I just checked the FAQ page, it seems like the fix I put in place yesterday (no accent #...) is working.

https://www.klipper3d.org/hu/FAQ.html

**Comment by ghost** [comment]
> 



> > Screenshot_20220512-053507~2
> > This section is also translated. But he didn't get on the page. This is the (Navigation) part if I know it.
> 
> The "Navigation" in Weblate doesn't work because it needs a ton of manual adjustment to the website's configuration file and I haven't implement it yet. I'll try to implement them in the near future, but I really don't have a clue at the moment.
> 
> I just checked the FAQ page, it seems like the fix I put in place yesterday (no accent #...) is working.
> 
> https://www.klipper3d.org/hu/FAQ.html

Screenshot_20220512-084629
I fixed FAQ everything back in English last night.
It was extra work then. I messed it up. I fixed the FAQ back last night. Here's how I did it: [Hogyan adományozhatok a projektnek?](#how-can-i-donate-to-the-project) but then how does it work? --> [Hogyan adományozhatok a projektnek?](#hogyan-adomanyozhatok-a-projektnek)

**Comment by dingyifei** [comment]
@AntoszHUN 

I think we had a misunderstanding, Please Read Everything Below!

what happened is the following:

1. I changed everything from English to Hungarian in #... without accent and wrote a comment about why FAQ isn't working
2. you put FAQ #... back to English (my description is probably unclear. The #... can't be in English, it needs to be matching the section titles without accents and symbols, and spaces replaced with `-`) 
3. I didn't merge the Weblate update that was made later and the change in 1 was applied. Right now what appeared on Klipper3d.org/hu/FAQ.html is what happened in 1.

I'm sorry for the confusion, English isn't my primary language, and some sentences I wrote yesterday might be misleading. 

This doesn't work: 
`[test](#hello world!)`
[test](#hello world!)

This work:
`[test](#hello-world)`
[test](#hello-world)

Language in #... doesn't matter!




# Hello world!!!

**Comment by ghost** [comment]
> @AntoszHUN
> 
> I think we had a misunderstanding, what happened is the following:
> 
> 1. I changed everything from English to Hungarian in #... without accent and wrote a comment about why FAQ isn't working
> 2. you put FAQ #... back to English (my description is probably unclear. The #... can't be in English, it needs to be matching the section titles without accents and symbols, and spaces replaced with `-`)
> 3. I didn't merge the Weblate update that was made later and the change in 1 was applied. Right now what appeared on Klipper3d.org/hu/FAQ.html is what happened in 1.
> 
> I'm sorry for the confusion, English isn't my primary language and some sentences I wrote yesterday might be misleading
> 
> This doesn't work: `[test](#hello world!)` [test](#hello world!)
> 
> This work: `[test](#hello-world)` [test](#hello-world)
> 
> # Hello world!!!

I understand! I'm sorry! I was puzzled. Then what is in parentheses () can remain the same in Hungarian only without an accent and end-of-sentence.

**Comment by dingyifei** [comment]
Correct.

**Comment by ghost** [comment]
> Correct.

Good. Then I'll review it all over the weekend. Weblate page and I'll fix everything. There are definitely other bugs. I'll let you know when you're done.

**Comment by dingyifei** [comment]
If you want to learn more about fixing the navigation table, you can look at https://github.com/Klipper3d/klipper/tree/master/docs/_klipper3d 

I'm not sure if I can fix this issue in the next two weeks since I have four exams in the next ten days.

**Comment by ghost** [comment]
> 



> If you want to learn more about fixing the navigation table, you can look at https://github.com/Klipper3d/klipper/tree/master/docs/_klipper3d
> 
> I'm not sure if I can fix this issue in the next two weeks since I have four exams in the next ten days.

No problem. Good luck with the exams!

**Comment by KevinOConnor** [comment]
Good luck on your exams!  Thanks for working on this!

-Kevin

**Comment by ghost** [comment]
Hello Masters!

During tonight (May 15, 2022 - 8:16 pm) I fixed a few bugs in the (Contact) menu. LINKs don't work there either. I hope it will be good now. I would add that I have also translated the newly inserted texts. Thank you in advance for your reply!

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

**Comment by dingyifei** [comment]
> Hello Masters!
> 
> During tonight (May 15, 2022 - 8:16 pm) I fixed a few bugs in the (Contact) menu. LINKs don't work there either. I hope it will be good now. I would add that I have also translated the newly inserted texts. Thank you in advance for your reply!
> 
> Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)

I just merged your changes. Some links are still incorrect. For example, in

```
A [Klipper Közösségi Fórumban](#klipper-kozossegi-forum) is kereshetsz hasonló kérdéseket.
```

The link is `#klipper-kozossegi-forum` but this title doesn't exist on the Contact page. The correct link is `#kozossegi-forum`. I have fixed these through Weblate find and replace tool.

**Comment by ghost** [comment]
> 



> > Hello Masters!
> > During tonight (May 15, 2022 - 8:16 pm) I fixed a few bugs in the (Contact) menu. LINKs don't work there either. I hope it will be good now. I would add that I have also translated the newly inserted texts. Thank you in advance for your reply!
> > Signed-off-by: AntoszHUN [zsikaiantal@gmail.com](mailto:zsikaiantal@gmail.com)
> 
> I just merged your changes. Some links are still incorrect. For example, in
> 
> ```
> A [Klipper Közösségi Fórumban](#klipper-kozossegi-forum) is kereshetsz hasonló kérdéseket.
> ```
> 
> The link is `#klipper-kozossegi-forum` but this title doesn't exist on the Contact page. The correct link is `#kozossegi-forum`. I have fixed these through Weblate find and replace tool.

Hi! Thanks. I see I didn't pay much attention. Thanks for the fix.

**Comment by ghost** [comment]
Hi! I watched. The 3. 4. and 6. 7. links marked in the image do not work. Also, the link at the bottom of the page (Klipper Community Discord) does not work. I also attached a picture of this.

Screenshot_20220517-225434~2
Screenshot_20220517-230847~2

**Comment by dingyifei** [comment]
imageimage

i think the correct link is discord-cseveges instead of klipper-discord-cseveges. My last midterm is tomorrow, I'll fix all these after that.

**Comment by ghost** [comment]
> 



> imageimage
> 
> i think the correct link is discord-cseveges instead of klipper-discord-cseveges. My last midterm is tomorrow, I'll fix all these after that.

All right. Thanks!

**Comment by dingyifei** [comment]
klipper #5519

**Comment by ghost** [comment]
I guess the titles don't match. I fixed this this morning. I think those menu items will work!

**Comment by ghost** [comment]
Super! My tip came in. I fixed it, it got in and I see it working. I still found bugs. I corrected.

**Comment by dingyifei** [comment]
> Super! My tip came in. I fixed it, it got in and I see it working. I still found bugs. I corrected.

i have opened a pull request in Klipper repository to add the table of content translation support. Once it's merged, the "Navigation" will show up correctly.

**Comment by ghost** [comment]
> 



> > Super! My tip came in. I fixed it, it got in and I see it working. I still found bugs. I corrected.
> 
> i have opened a pull request in Klipper repository to add the table of content translation support. Once it's merged, the "Navigation" will show up correctly.

Super. Thanks!

**Pull request merged**
